version: '3'

services:
  web01:
    image: porchn/php5.6.28-apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - apache-www:/var/www
    environment:
      - TZ=Asia/Bangkok
    networks:
      - webnetwork
    deploy:
      restart_policy:
        condition: on-failure
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnetwork
volumes:
  apache-www:
    driver: local
    driver_opts:
      type: none
      device: /webtools/www
      o: bind
networks:
  webnetwork:
    driver: overlay

