version: '3'

services:
  web01:
    image: porchn/php5.6.28-apache
    volumes:
      - apache-www:/var/www
      - ./apache/conf:/etc/apache2/sites-enabled
    environment:
      - TZ=Asia/Bangkok
    networks:
      - web-network
    deploy:
      restart_policy:
        condition: on-failure
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - web-network
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/caches:/data-cache
    environment:
      - TZ=Asia/Bangkok
      - NGINX_PORT=80
    depends_on:
      - web01
    networks:
      - web-network

volumes:
  apache-www:
    driver: local
    driver_opts:
      type: none
      device: /Users/pichaichin/Sites/testswarm/www
      o: bind
networks:
  web-network:
    external: true

